services:
  # Service pour le frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Make sure the path to your Dockerfile is correct
    ports:
      - "80:80"  # Expose port 80 for the frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
